// =====================================================================
//  JulieAgent — Campaign marketing orchestrator agent
//
//  Julie is a workflow-type agent that coordinates:
//  1. SqlAgent (type: agent) — generates T-SQL from natural language
//  2. Function App (type: openapi) — executes the T-SQL against the DB
//  3. MarketingAgent (type: agent) — generates personalized messages
//
//  The final result is a campaign JSON with emails.
//
//  Tools:
//    - SqlAgent        → agent that generates the T-SQL query
//    - SqlExecutor     → OpenAPI tool that executes the SQL against the DB
//    - MarketingAgent  → agent that generates marketing messages
//
//  The Function App URL is configured in appsettings.json
//  (FunctionAppBaseUrl). If not configured, Julie is created
//  without the OpenAPI tool (pending deployment).
// =====================================================================

using System.Text.Json;
using Azure.AI.Projects.OpenAI;

namespace JulieAgent;

public static class JulieOrchestrator
{
    public const string Name = "Julie";

    public static string Instructions => """
        You are Julie, the planning and orchestration agent for Contoso Retail
        marketing campaigns.

        Your responsibility is to coordinate the creation of personalized marketing
        campaigns for specific customer segments.

        When you receive a campaign request, follow these steps:

        1. EXTRACTION: Analyze the user's prompt and extract the description
           of the customer segment. Summarize that description in a clear phrase.

        2. SQL GENERATION: Invoke SqlAgent, passing it the segment description.
           SqlAgent will return a T-SQL query.

        3. SQL EXECUTION: Send the T-SQL to your OpenAPI tool (SqlExecutor)
           to execute it against the database. The tool will return the
           results as customer data.

        4. PERSONALIZED MARKETING: For EACH returned customer, invoke
           MarketingAgent, passing it the customer's name and their favorite category.
           MarketingAgent will search for relevant events on Bing and generate a
           personalized message.

        5. FINAL ORGANIZATION: With all generated messages, organize the
           result as a campaign JSON using the following format:

        ```json
        {
          "campaign": "Descriptive campaign name",
          "generatedAt": "YYYY-MM-DDTHH:mm:ss",
          "totalEmails": N,
          "emails": [
            {
              "to": "email@example.com",
              "customerName": "First Last",
              "favoriteCategory": "Category",
              "subject": "Automatically generated email subject",
              "body": "Personalized marketing message"
            }
          ]
        }
        ```

        RULES:
        - The "subject" field must be an attractive and relevant email subject line.
        - The "body" field is the message generated by MarketingAgent for that customer.
        - Always respond in English.
        - If a customer does not have an email, omit them from the result.
        - Generate a descriptive name for the campaign based on the segment.
        """;

    /// <summary>
    /// Builds the Julie agent definition as a WorkflowAgentDefinition
    /// using CSDL YAML, compatible with the current API.
    /// </summary>
    public static WorkflowAgentDefinition GetAgentDefinition(string modelDeployment, JsonElement? openApiSpec = null)
    {
        _ = modelDeployment;
        _ = openApiSpec;

        var workflowYaml = $$"""
kind: Workflow
trigger:
  kind: OnActivity
workflow:
  actions:
    - kind: InvokeAzureAgent
      id: sql_step
      agent:
        name: {{SqlAgent.Name}}
      conversationId: =System.ConversationId
      input:
        messages: =System.LastMessage
      output:
        messages: Local.SqlMessages

    - kind: InvokeAzureAgent
      id: marketing_step
      agent:
        name: {{MarketingAgent.Name}}
      conversationId: =System.ConversationId
      input:
        messages: =Local.SqlMessages
      output:
        autoSend: true
""";

        return ProjectsOpenAIModelFactory.WorkflowAgentDefinition(workflowYaml: workflowYaml);
    }
}
